### ISSUE TITLE
B-nodes being displayed as live http hyperlinks

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/sedgemoor-data#12] opened 2015-01-18 14:33 UTC
For example, in a describedBy statement.

**Comment by ijdickinson** [comment] 2015-01-18 21:24
You don't state whether this is in the Elda output, but if it is it's likely a duplicate of epimorphics/elda#115.

**Comment by bwmcbride** [comment] 2015-01-19 09:27
Looks like the same problem.  I'll keep this tracker entry so I have a list of issue affecting the Sedgemoor system.

**Closed as completed** 2015-01-23 19:19 UTC
Labels: bug
